<a href="https://colab.research.google.com/github/PosgradoMNA/Actividades-de-aprendizaje.-Yocelin-Juarez-Arroyo-A00819828/blob/main/IBM_Python_Module_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy 1D Arrays

In [7]:
#Para empezar a trabajar con NumPy, lo primero que debemos hacer es importarlo
import numpy as np
#Lo que hice fue acortar en nomre NumPy como np, para facilitar el acceso

In [13]:
a = np.array([25, 45, 82, 37, 71])
a
#Creamor un numpy

array([25, 45, 82, 37, 71])

In [15]:
#Podemos acceder a cualquier termino mediante su índice
print(a[2])

82


In [18]:
#Cambiar valores en el Numpy
a[1]=999
a

array([ 25, 999,  82,  37,  71])

In [20]:
#Partir el Numpy para conseguir otro
b=a[0:3]
b

array([ 25, 999,  82])

In [21]:
select=[0,2,3,4]
select
#Creamor valores que queremos seleccionar

[0, 2, 3, 4]

In [22]:
c=a[select]
c
#Solo no da un numpy con las posiciones que elegimos en el punto anterior

array([25, 82, 37, 71])

In [23]:
#Podemos realizar operaciones entren numpys
#SUMA
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
arr3=np.add(arr1,arr2)
arr3

array([30, 32, 34, 36, 38, 40])

In [24]:
#RESTA
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
arr3=np.subtract(arr1,arr2)
arr3

array([-10,  -1,   8,  17,  26,  35])

In [25]:
#MULTIPLICACION
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 1, 2, 3, 4, 5])
arr3=np.multiply(arr1,arr2)
arr3

array([ 20,  20,  60, 120, 200, 300])

In [26]:
#DIVISIÓN
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])
arr3=np.divide(arr1,arr2)
arr3

array([ 3.33333333,  4.        ,  3.        ,  5.        , 25.        ,
        1.81818182])

In [29]:
#PRODUCTO PUNTO
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])
np.dot(arr1,arr2)

2830

#Numpy 2D Arrays

In [31]:
#para crear unn Numpy de 2 dimensiones primero hacemos una lista
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [32]:
A = np.array(a)
A
#y luego lo convertimos en Numpy

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [34]:
#Podemos acceder a diferentes posiciones en el Numpy
A[1,2]

23

In [36]:
A[2,2]

33

In [37]:
A[0,0]

11

In [38]:
#Podemos acceder a puntos específicos o grupos
A[0][0:2]

array([11, 12])

In [39]:
#Otro ejemplo de lo anterior es el siguiente
A[0:2, 2]

array([13, 23])

In [42]:
#Podemos hacer operaciones entre numpy, por ejmplo, declaramos dos numpy
X = np.array([[1, 0], [0, 1]]) 
X
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [43]:
print(X)
print(Y)

[[1 0]
 [0 1]]
[[2 1]
 [1 2]]


In [44]:
#Realizamos una suma entre las numpyes
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [45]:
#Así mismo podemos multiplicarlas por ellas mismas o por otra numpy
Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [47]:
#A continuación las multipliqué entre ellas
Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [50]:
#Ahora vamos a calcular el producto punto
Z = np.dot(X,Y)
Z

array([[2, 1],
       [1, 2]])

In [51]:
np.sin(Z)

array([[0.90929743, 0.84147098],
       [0.84147098, 0.90929743]])

In [52]:
C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [53]:
C.T
#La función anterior es para crear una traspuesta de la matriz

array([[1, 2, 3],
       [1, 2, 3]])

#Simple APIs

Un API es un interfaz de programa de operaciones y son creados para hacer posible la interacción de dos sistemas informáticos.

In [54]:
#Para comenzar instalamos randomuser
!pip install randomuser

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5084 sha256=e958da1094f522d13bb3217f1c26e4c0e29ae5373561a863bdc26206404a4a32
  Stored in directory: /root/.cache/pip/wheels/21/10/7b/c13bc3e24a3c1000a34554802ad8aa0ff27df56366998a0473
Successfully built randomuser


In [55]:
#Y fueron cargadas las librerias necesarias
from randomuser import RandomUser
import pandas as pd

In [56]:
r = RandomUser()

In [57]:
some_list = r.generate_users(10)
some_list

In [58]:
name = r.get_full_name()

In [59]:
for user in some_list:
    print (user.get_full_name()," ",user.get_email())

Deniz Çetin   deniz.cetin@example.com
Oscar Wiesmann   oscar.wiesmann@example.com
Maeve Silva   maeve.silva@example.com
Marsha Mills   marsha.mills@example.com
Gerardo Medina   gerardo.medina@example.com
Volkan Samancı   volkan.samanci@example.com
Alvin Rhodes   alvin.rhodes@example.com
Julião Farias   juliao.farias@example.com
Nawfal Sikkema   nawfal.sikkema@example.com
Eden Wang   eden.wang@example.com


In [60]:
for user in some_list:
    print (user.get_picture())

https://randomuser.me/api/portraits/men/45.jpg
https://randomuser.me/api/portraits/men/65.jpg
https://randomuser.me/api/portraits/women/1.jpg
https://randomuser.me/api/portraits/women/2.jpg
https://randomuser.me/api/portraits/men/5.jpg
https://randomuser.me/api/portraits/men/84.jpg
https://randomuser.me/api/portraits/men/4.jpg
https://randomuser.me/api/portraits/men/17.jpg
https://randomuser.me/api/portraits/men/88.jpg
https://randomuser.me/api/portraits/women/73.jpg


In [61]:
def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
      
    return pd.DataFrame(users)     

In [62]:
get_users()

Name  Gender            City              State  \
0          Loris Morin    male           Nîmes          Finistère   
1  Tony Van der Avoird    male      Oudeschoot          Flevoland   
2        Helmine Takle  female         Leikong    Møre og Romsdal   
3   Macit Süleymanoğlu    male      Kırklareli               Ordu   
4        Thekla Gröger  female     Lichtenfels    Rheinland-Pfalz   
5          Mandy Owens  female         Glasgow   County Fermanagh   
6           رهام موسوی    male           بوشهر             گلستان   
7            Tom Hicks    male  Sunshine Coast  Western Australia   
8        Hudson Fortin    male         Keswick       Saskatchewan   
9    Charlotte Kennedy  female         Shannon          Waterford   

                            Email                       DOB  \
0         loris.morin@example.com  1994-01-08T03:36:31.067Z   
1   tony.vanderavoird@example.com  1946-08-05T05:03:03.647Z   
2       helmine.takle@example.com  1997-09-06T19:02:30.574Z   
3  macit.suleymanoglu@example.com  1951-03-09T00:44:31.644Z   
4       thekla.groger@example.com  1957-08-23T12:42:08.351Z   
5         mandy.owens@example.com  1964-09-22T01:31:03.479Z   
6           rhm.mwswy@example.com  1983-03-11T06:45:11.387Z   
7           tom.hicks@example.com  1997-02-23T08:32:10.975Z   
8       hudson.fortin@example.com  1975-11-08T06:45:08.564Z   
9   charlotte.kennedy@example.com  1992-06-25T21:13:06.371Z   

                                            Picture  
0    https://randomuser.me/api/portraits/men/97.jpg  
1    https://randomuser.me/api/portraits/men/94.jpg  
2  https://randomuser.me/api/portraits/women/47.jpg  
3    https://randomuser.me/api/portraits/men/38.jpg  
4  https://randomuser.me/api/portraits/women/21.jpg  
5  https://randomuser.me/api/portraits/women/65.jpg  
6     https://randomuser.me/api/portraits/men/3.jpg  
7    https://randomuser.me/api/portraits/men/86.jpg  
8    https://randomuser.me/api/portraits/men/43.jpg  
9  https://randomuser.me/api/portraits/women/36.jpg

In [63]:
df1 = pd.DataFrame(get_users())  